In [1]:
import numpy as np

# Q1

In [6]:
def func(vector,n):
    a=np.array(vector)
    mat = np.array([a**(n-1-i) for i in range(n)])
    return mat.reshape(n,a.shape[0]).T

In [8]:
print(func([1,2,3,4,5],3))

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


# Q2

In [9]:
def moving_avg(arr,k):
    mov_arr = [[arr[j] for j in range(i,i+k)] for i in range(len(arr) - k + 1)]
    mov_arr = np.array(mov_arr)
    mov_avgs = [i.mean() for i in mov_arr]
    return mov_avgs

In [10]:
arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

In [13]:
print('moving avgs for k=:',','.join(moving_avg(arr,3)))

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]